Communication-Protocol
=====================

== Server Events
==== LOGIN_REQUEST_ANSWER

The object the clients sends to identify itself at the server.

[source/json]
	{
	    "op" : 1,
	    "data" :
	    {
	        "username" : "USERNAME",
	        "password" : "PASSWORD"
	    },
	    "type" : "LOGIN_REQUEST_ANSWER"
	}

==== PLAYER_ACTION_ANSWER

Contains the information of the decisions a player made on his turn.

[source/json]
    {
        "op":1,
        "data":
        {
            "action": "ACTION",
            "betAmount": value,
            "isAllIn": boolean //dunno maybe interesting
        }
        "type": "PLAYER_ACTION_ANSWER"
    }

==== TABLE_JOIN_REQUEST

If the client wants to join a table.

[source/json]
    {
        "op":1,
        "data":
        {
            "table": TABLE_IDENTIFCATION
        }
        "type": "TABLE_JOIN_REQUEST"
    }

==== OPEN_TABLES_REFRESH

Sends the open tables information.

[source/json]
    {
        "op":1,
        "data":{},
        "type": "OPEN_TABLES_REFRESH"
    }

== Client Events

==== LOGIN_REQUEST

If a client connectes to the server, a login request is send.

[source/json]
	{
	    "op" : 1,
	    "data" : {},
	    "type" : "LOGIN_REQUEST"
	}


==== LOGIN_RESULT

Information for the client if the log-in was successful.

[source/json]
    {
        "op" : 1,
        "data" :
        {
            "valid" : "TRUE/
            "reason"" : "STRING"
        },
        "type" : "LOGIN_RESULT"
    }

==== OPEN_TABLES

Contains all the possible tables the client can join.

[source/json]
    {
        "op":1,
        "data":
        {
            "tables": [
                {
                    "id":ID,
                    "currentPlayers": value,
                    "maximumPlayers": value,
                },
                ...
            ]
        },
        "type": "OPEN_TABLES"
    }

==== ON_TABLE_JOIN

If you join a table, you receive and JSONobject with all usefull information
from the table, eg. a list of all already connected players,...

[source/json]
    {
        "op":1,
        "data":
        {
            "players": [PlayerObject, PlayerObject, ...]
            //Todo
        }
    }

==== ON_TABLE_LEAVE

[TODO] todo

==== PLAYER_JOINS_TABLE

If you already connected to the table, and the game hasn't started yet, so another
play can still join.

[source/json]
    {
        "op":1,
        "data":
        {
            "player": PlayerObj
        }
        "type": "PLAYER_JOINS_TABLE"
    }

==== PLAYER_LEAVES_TABLE

[TODO] todo

==== PLAYER_ACTION_REQUEST

If it is the turn of a player. The server will send him an request with the
important for the player. The client will have a time limit

[source/json]
    {
        "op":1,
        "data":
        {
            "actions": ["FOLD","BET", "CHECK"] || ["FOLD", "RAISE", "CALL"],
            "currentPlayerBet" : value,
            "currentTableBet" : value,
            "maximumPlayerBet" : value
        }
        "type": "PLAYER_ACTION_REQUEST"
    }

==== ROUND_UPDATE_START

If a new round starts, the information will be send

[source/json]
    {
        "op":1,
        "data":
        {
            "dealer": PlayerObject,
            "smallBlind": PlayerObject,
            "bigBlind": PlayerObject
        },
        "type": "ROUND_UPDATE_START"
    }

==== ROUND_UPDATE_CARD_DRAW

A player draws a card (in PREFLOP)

[source/json]
    {
        "op":1,
        "data":
        {
            "card": CARD,
        },
        "type": "ROUND_UPDATE_CARD_DRAW"
    }

==== ROUND_UPDATE_ROUND

If the games goes from one turn to the next turn and contains the important
information.

[source/json]
    {
        "op":1,
        "data":
        {
            "oldTurn": "PREFLOP" || "FLOP" || "TURN" || ...,
            "newTurn": "PREFLOP" || "FLOP" || "TURN" || ...,
            "newBoardCard": CARD
        }
        "type": "ROUND_UPDATE_TURN"
    }


==== ROUND_UPDATE_SHOWDOWN

Will contain the information for the showdown.

[source/json]
    {
        "op":1,
        "data":
        {
            //todo
        },
        "type": "ROUND_UPDATE_SHOWDOWN"
    }

==== ROUND_UPDATE_PLAYER

After a player made an action, the server distributes all the information
to the other players.

[source/json]
    {
        "op":1,
        "data":
        {
            "player": PlayerObject,
            "action": "ACTION"
            "betAmount": value
        }
        "type": "ROUND_UPDATE_PLAYER"
    }
