Communication-Protocol
=====================

== Server Events
==== LOGIN_REQUEST_ANSWER

The object the clients sends to identify itself at the server.
``
``[source/json]
	{
	    "op" : 1,
	    "data" :
	    {
	        "username" : "USERNAME",
	        "password" : "PASSWORD"
	    },
	    "type" : "LOGIN_REQUEST_ANSWER"
	}

==== PLAYER_ACTION_ANSWER

Contains the information of the decisions a player made on his turn.

[source/json]
    {
        "op":1,
        "data":
        {
            "tableId": ID,
            "action": "ACTION",
            "betAmount": value,
            "isAllIn": boolean //dunno maybe interesting
        }
        "type": "PLAYER_ACTION_ANSWER"
    }

==== TABLE_JOIN_REQUEST

If the client wants to join a table.

[source/json]
    {
        "op":1,
        "data":
        {
            "tableId": ID
        }
        "type": "TABLE_JOIN_REQUEST"
    }

==== OPEN_TABLES_REFRESH

Sends the open tables information.

[source/json]
    {
        "op":1,
        "data":{},
        "type": "OPEN_TABLES_REFRESH"
    }

== Client Events

==== LOGIN_REQUEST

If a client connects to the server, a login request is send.

[source/json]
	{
	    "op" : 1,
	    "data" : {},
	    "type" : "LOGIN_REQUEST"
	}
//Done

==== LOGIN_RESULT

Information for the client if the log-in was successful.

[source/json]
    {
        "op" : 1,
        "data" :
        {
            "valid" : "TRUE/FALSE,
            "reason"" : "STRING",
            "playerId" : "STRING"
        },
        "type" : "LOGIN_RESULT"
    }
//Done

==== OPEN_TABLES

Contains all the possible tables the client can join.

[source/json]
    {
        "op":1,
        "data":
        {
            "tables": [
                {
                    "tableId":ID,
                    "currentPlayers": value,
                    "neededPlayers": value,
                },
                ...
            ]
        },
        "type": "OPEN_TABLES"
    }
//Done

==== ON_TABLE_JOIN

If you join a table, you receive a JSONobject with all usefull information
from the table, eg. a list of all already connected players,...

[source/json]
    {
        "op":1,
        "data":
        {
            "players": [PlayerObject, PlayerObject, ...]
            "tableId" : tableId,
            "success : boolean
        }
        "type": "ON_TABLE_JOIN"
    }
//Done

==== ON_TABLE_LEAVE

[source/json]
    {
        "op":1,
        "data":
        {
            "reason" : STRING
        }
        "type" : "ON_TABLE_LEAVE"
    }
//Done

==== PLAYER_JOINS_TABLE

If you already connected to the table, and the game hasn't started yet, so another
play can still join.

[source/json]
    {
        "op":1,
        "data":
        {
            "player": PlayerObj
        }
        "type": "PLAYER_JOINS_TABLE"
    }
//Done

==== PLAYER_LEAVES_TABLE

send player which leaves

[source/json]
    {
        "op":1,
        "data":
        {
            "playerId": playerId
            "reason" : string
        }
        "type": "PLAYER_LEAVES_TABLE"
    }
//Done

==== PLAYER_ACTION_REQUEST

If it is the turn of a player. The server will send him an request with the
important for the player. The client will have a time limit

[source/json]
    {
        "op":1,
        "data":
        {
            "actions": 0 || 1,
            //0 = prebet, 1 = pastbet
            //"currentPlayerBet" : value,
            //"currentTableBet" : value,
            "maximumPlayerBet" : value          //Better let the server calculate this for you
        }
        "type": "PLAYER_ACTION_REQUEST"
    }
//Done, partially, needs to move logic there

==== ROUND_UPDATE_START

If a new round starts, the information will be send

[source/json]
    {
        "op":1,
        "data":
        {
            "dealer": PlayerId,
            "smallBlind": PlayerId,
            "bigBlind": PlayerId,
        },
        "type": "ROUND_UPDATE_START"
    }
//Done

==== ROUND_UPDATE_PAY_BLINDS

every client received this event for information purpose
every client
[source/json]
    {
        "op":1,
        "data":
        {
            "playerId" : playerId,
            "blindtype" : small/big
            "allin": true/false
        },
        "type": "ROUND_UPDATE_PAY_BLINDS"
    }


==== ROUND_UPDATE_CARD_DRAW

A player gets a card (in PREFLOP)

[source/json]
    {
        "op":1,
        "data":
        {
            "card": CARD
        },
        "type": "ROUND_UPDATE_CARD_DRAW"
    }

==== ROUND_UPDATE_ROUND

If the games goes from one turn to the next turn and contains the important
information.

[source/json]
    {
        "op":1,
        "data":
        {
            "oldTurn": "PREFLOP" || "FLOP" || "TURN" || ...,
            "newTurn": "PREFLOP" || "FLOP" || "TURN" || ...,
            "newBoardCard": CARD
        }
        "type": "ROUND_UPDATE_TURN"
    }


==== ROUND_UPDATE_SHOWDOWN_PRE_PAYMENT

Will contain the information for the showdown.

[source/json]
    {
        "op":1,
        "data":
        {
            "information" : [ {
                        "playerId": playerId,
                        "card1" : card,
                        "card2" : card
                   }, ...
                ]
        },
        "type": "ROUND_UPDATE_SHOWDOWN"
    }

==== ROUND_UPDATE_SHOWDOWN_POST_PAYMENT

Will contain the information for the showdown.

[source/json]
    {
        "op":1,
        "data":
        {
            "winners": [{
                "playerId":playerId,
                "winAmount": value,
                "money"}
               ]
        },
        "type": "ROUND_UPDATE_SHOWDOWN"
    }

==== ROUND_UPDATE_PLAYER

After a player made an action, the server distributes all the information
to the other players.

[source/json]
    {
        "op":1,
        "data":
        {
            "playerId": playerId,
            "action": BettingOperation,
            "gameState" : FOLD || ALLIN || PLAYING,
            "betAmount": value,
            "money" : value,
            "totalBetAmount" : value,

            //of table
            "currentRoundBet" : value,
            "pot" : value
        }
        "type": "ROUND_UPDATE_PLAYER"
    }
//Done so far, still missing some values

==== ROUND_UPDATE_CHOOSER_PLAYER

Informs other clients which client has to take his choice.

[source/json]
    {
        "op":1,
        "data":
        {
            "playerId": playerId
        }
        "type": "ROUND_UPDATE_CHOOSER_PLAYER"
    }